// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp5QEhuYVYpMx8BZllcVs6E3LmhjRd4sI',
    appId: '1:29425779721:web:db8ff5b7400ba498e8e4d8',
    messagingSenderId: '29425779721',
    projectId: 'haircutlog-1514a',
    authDomain: 'haircutlog-1514a.firebaseapp.com',
    storageBucket: 'haircutlog-1514a.appspot.com',
    measurementId: 'G-6KDJGJM2TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBSuyQpRCvKNEyldp0VZSRBffFt6Y0Ods',
    appId: '1:29425779721:android:0e119ca17d33b109e8e4d8',
    messagingSenderId: '29425779721',
    projectId: 'haircutlog-1514a',
    storageBucket: 'haircutlog-1514a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApCw5jst1BjinSCIpBdQjjtCu6OdCMPTc',
    appId: '1:29425779721:ios:cb595f7bfc9454f5e8e4d8',
    messagingSenderId: '29425779721',
    projectId: 'haircutlog-1514a',
    storageBucket: 'haircutlog-1514a.appspot.com',
    iosClientId: '29425779721-s3cgp7oanrh5tcgf2haelmr8faejl44a.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiverrHaircut',
  );
}
